import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1777267533869 implements MigrationInterface {
    name = 'Init1777267533869'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP CONSTRAINT "fk_nt_user"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "fk_recipes_parent"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "fk_recipes_user"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP CONSTRAINT "fk_ng_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nt_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rec_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rec_public"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rec_category_diff"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rec_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rec_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ng_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ng_startdate"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "chk_recipes_difficulty"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "chk_recipes_category"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "chk_recipes_rating"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP CONSTRAINT "uq_nt_user_date"`);
        await queryRunner.query(`CREATE TABLE "nutrition_profiles" ("id" character varying NOT NULL, "user_id" character varying NOT NULL, "diet_type" character varying NOT NULL DEFAULT 'omnivore', "excluded_ingredients" text array NOT NULL DEFAULT '{}', "excluded_categories" text array NOT NULL DEFAULT '{}', "max_daily_calories" integer, "target_protein" integer, "target_carbs" integer, "target_fat" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ca03d92bd2eb9eec3ac2a037527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_nutrition_profile_user_id" ON "nutrition_profiles" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "is_custom"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "isCustom" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "nutrition_tracker_meals" DROP CONSTRAINT IF EXISTS "fk_ntm_tracker"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP CONSTRAINT "pk_nutrition_trackers"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD "id" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD CONSTRAINT "PK_915b8a497207652dda4a7e8eb78" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD "user_id" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_calories" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_protein" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_carbohydrates" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_fat" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_fiber" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" DROP CONSTRAINT IF EXISTS "fk_ri_recipe"`);
        await queryRunner.query(`ALTER TABLE "recipe_instructions" DROP CONSTRAINT IF EXISTS "fk_rinstr_recipe"`);
        await queryRunner.query(`ALTER TABLE "recipe_tags" DROP CONSTRAINT IF EXISTS "fk_rtag_recipe"`);
        await queryRunner.query(`ALTER TABLE "nutrition_tracker_meals" DROP CONSTRAINT IF EXISTS "fk_ntm_recipe"`);
        await queryRunner.query(`ALTER TABLE "meal_plan_entries" DROP CONSTRAINT IF EXISTS "fk_mpe_recipe"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "pk_recipes"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "id" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "PK_8f09680a51bf3669c1598a21682" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "user_id" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "parent_recipe_id"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "parent_recipe_id" character`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "difficulty"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "difficulty" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "rating" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "rating" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_calories" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_calories" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_protein" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_protein" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_carbohydrates" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_carbohydrates" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fat" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fat" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fiber" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fiber" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sugars" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sugars" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sodium" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sodium" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "ni_serving_size"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "ni_serving_size" character varying`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_servings_per_recipe" SET NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."uq_rf_user_recipe"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rf_recipe_rating"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP CONSTRAINT "pk_recommendation_feedbacks"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD CONSTRAINT "PK_538c99577bef661f2eff1325862" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP COLUMN "recipe_id"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD "recipe_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP CONSTRAINT "pk_nutrition_goals"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD "id" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD CONSTRAINT "PK_843d6ec58065c4f34aabc9052a3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD "user_id" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_protein_grams" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_carbohydrates_grams" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_fat_grams" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_fiber_grams" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_sugar_limit_grams" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_sodium_limit_mg" TYPE numeric`);
        await queryRunner.query(`CREATE INDEX "idx_nutrition_trackers_date" ON "nutrition_trackers" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_recipes_public" ON "recipes" ("is_public") `);
        await queryRunner.query(`CREATE INDEX "idx_recipes_difficulty" ON "recipes" ("difficulty") `);
        await queryRunner.query(`CREATE INDEX "idx_recipes_category" ON "recipes" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_rf_user_recipe" ON "recommendation_feedbacks" ("user_id", "recipe_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rf_recipe_rating" ON "recommendation_feedbacks" ("recipe_id", "rating") `);
        await queryRunner.query(`CREATE INDEX "idx_nutrition_goals_is_active" ON "nutrition_goals" ("is_active") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_nutrition_goals_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rf_recipe_rating"`);
        await queryRunner.query(`DROP INDEX "public"."uq_rf_user_recipe"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recipes_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recipes_difficulty"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recipes_public"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nutrition_trackers_date"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_sodium_limit_mg" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_sugar_limit_grams" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_fiber_grams" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_fat_grams" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_carbohydrates_grams" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ALTER COLUMN "goal_protein_grams" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD "user_id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP CONSTRAINT "PK_843d6ec58065c4f34aabc9052a3"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD "id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD CONSTRAINT "pk_nutrition_goals" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP COLUMN "recipe_id"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD "recipe_id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD "user_id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP CONSTRAINT "PK_538c99577bef661f2eff1325862"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD "id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recommendation_feedbacks" ADD CONSTRAINT "pk_recommendation_feedbacks" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE INDEX "idx_rf_recipe_rating" ON "recommendation_feedbacks" ("rating", "recipe_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_rf_user_recipe" ON "recommendation_feedbacks" ("recipe_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_servings_per_recipe" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "ni_serving_size"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "ni_serving_size" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sodium" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sodium" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sugars" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_sugars" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fiber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fiber" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fat" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_fat" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_carbohydrates" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_carbohydrates" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_protein" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_protein" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_calories" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "ni_calories" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "rating" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ALTER COLUMN "rating" TYPE numeric(3,2)`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "image_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "difficulty"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "difficulty" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "category" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "name" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "parent_recipe_id"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "parent_recipe_id" character(24)`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "user_id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "PK_8f09680a51bf3669c1598a21682"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "pk_recipes" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_fiber" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_fat" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_carbohydrates" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_protein" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ALTER COLUMN "total_calories" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD "user_id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP CONSTRAINT "PK_915b8a497207652dda4a7e8eb78"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD "id" character(24) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD CONSTRAINT "pk_nutrition_trackers" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP COLUMN "isCustom"`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD "is_custom" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DROP INDEX "public"."uq_nutrition_profile_user_id"`);
        await queryRunner.query(`DROP TABLE "nutrition_profiles"`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD CONSTRAINT "uq_nt_user_date" UNIQUE ("user_id", "date")`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "chk_recipes_rating" CHECK (((rating >= (0)::numeric) AND (rating <= (5)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "chk_recipes_category" CHECK (((category)::text = ANY ((ARRAY['breakfast'::character varying, 'lunch'::character varying, 'dinner'::character varying, 'snack'::character varying, 'dessert'::character varying, 'beverage'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "chk_recipes_difficulty" CHECK (((difficulty)::text = ANY ((ARRAY['easy'::character varying, 'medium'::character varying, 'hard'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_ng_startdate" ON "nutrition_goals" ("start_date", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ng_active" ON "nutrition_goals" ("is_active", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rec_parent" ON "recipes" ("parent_recipe_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rec_rating" ON "recipes" ("rating", "rating_count") `);
        await queryRunner.query(`CREATE INDEX "idx_rec_category_diff" ON "recipes" ("category", "difficulty") `);
        await queryRunner.query(`CREATE INDEX "idx_rec_public" ON "recipes" ("created_at", "is_public") `);
        await queryRunner.query(`CREATE INDEX "idx_rec_user_date" ON "recipes" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_nt_user_date" ON "nutrition_trackers" ("date", "user_id") `);
        await queryRunner.query(`ALTER TABLE "nutrition_goals" ADD CONSTRAINT "fk_ng_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "fk_recipes_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "fk_recipes_parent" FOREIGN KEY ("parent_recipe_id") REFERENCES "recipes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition_trackers" ADD CONSTRAINT "fk_nt_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
